// Two SKILL.md variants for the full and no-edges validation environments.
// browse.mjs is shared; only the skill description and workflow differ.

export const SKILL_FULL = `
---
name: "doc-drill"
description: "Progressive-disclosure browser for ACCEED-generated codebase documentation. Use this skill when you need to understand a documented codebase: exploring architecture, locating where code lives, tracing module relationships, reading classic interaction flows, or answering 'how does X work' questions."
---

# doc-drill

You have access to structured, hierarchical documentation generated by ACCEED. The docs are organized as a tree: a top-level graph per project, sub-graphs nested inside modules, markdown leaf pages at the bottom, and interaction flows for classic end-to-end cases.

**Do not try to dump everything at once.** Drill down one layer at a time, guided by relevance to the task.

## Documentation model

\`\`\`
{skillDir}/doc/{project}/
├── top.json              # project overview + top-level modules
├── flows.json            # typical cross-module interaction flows
├── {Module}/
│   ├── {Module}.json     # sub-graph: description, codeScope, child nodes
│   ├── {Leaf}.md         # leaf page: detailed doc for one component
│   └── {SubModule}/
│       ├── {SubModule}.json
│       └── ...
\`\`\`

A graph's child node either points to a deeper sub-graph (\`child.type == "graph"\`) or to a markdown leaf page (\`child.type == "page"\`). Each graph carries:
- \`description\` — what this module does
- \`codeScope\` — the exact source files/dirs this module documents
- \`nodes[]\` — child nodes with \`name\`, \`description\`, \`codeScope\`, \`edges[]\`, \`child\`

Edges between sibling nodes carry relationship types: \`calls\`, \`depends\`, \`data-flow\`, \`event\`, \`extends\`, \`composes\`.

## The browse tool

Use \`scripts/browse.mjs\` (located in the doc-drill skill directory) to navigate:

\`\`\`bash
# Get project overview — see all top-level modules
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project}

# Drill into a module — see its children and relationships
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} {ModuleName}

# Keep drilling into sub-modules
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} {Module}/{SubModule}

# Read a leaf page when you've found the right component
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} {Module}/{LeafName} --read

# Search: find nodes by keyword across all levels
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} --search {keyword}

# Read classic end-to-end flows
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} --flows
\`\`\`

## Progressive-disclosure workflow

Follow this discipline every time you need codebase context:

### 1. Orient — top-level overview
Run browse with just the project name. Read the module list, their descriptions, and edges to understand the high-level architecture. **Stop here if the task only needs architectural understanding.**

### 2. Classic cases — flows
For cross-module behavior, user journeys, request lifecycles, sync jobs, or "how does this work end to end?" questions, run browse with \`--flows\` before drilling. Use the participants, doc paths, and code references as navigation hints. If \`flows.json\` is missing, continue with top / graph / page reads and source inspection.

### 3. Locate — drill into module
Pick the 1–2 most relevant modules based on descriptions and \`codeScope\`. Drill into them. Read child node descriptions and edges. **Stop here if you can now identify the right component.**

### 4. Focus — read leaf page
Once you've identified the specific component, read its \`.md\` page with \`--read\`. You now have detailed implementation docs: file-by-file breakdowns, data flows, key APIs.

### 5. Search — when unsure
If you can't tell which module to drill into, use \`--search\` with a keyword. The results tell you the matching node's module path so you can jump straight to the right depth.

## Key principles

- **Lazy loading**: Never read leaf pages until you've confirmed they're relevant via the graph hierarchy. Each page can be 5–15 KB — loading everything wastes context
- **Flow-guided tracing**: For end-to-end behavior, start from \`--flows\`, then drill only into modules and pages named by the relevant case
- **Edge-guided navigation**: The \`edges\` array tells you which siblings interact. Tracing a data flow or call chain? Follow the edges rather than reading every child
- **codeScope is ground truth**: When mapping docs back to source files, read \`codeScope\`. It lists the exact files/dirs a node documents
- **Breadth before depth**: At each level, scan all node descriptions first before drilling. Don't commit to the first plausible match

## Output conventions

When citing documentation findings:
- Use the module path as the citation: \`Core/SessionEngine/TurnLifecycle\`
- For end-to-end behavior, mention the flow title and participant path(s) you used
- Mention source files from \`codeScope\` when the user needs to edit code
- If a question spans multiple modules, trace the edges between them to explain the connection
`.trimEnd();

export const SKILL_NO_EDGES = `
---
name: "doc-drill"
description: "Progressive-disclosure browser for ACCEED-generated codebase documentation (tree-only variant). Use this skill to explore a documented codebase by navigating the module hierarchy and reading leaf pages. Semantic edges and interaction flows are not available in this documentation set — locate information through descriptions, search, and leaf page content."
---

# doc-drill (tree-only)

You have access to hierarchical documentation generated by ACCEED. The docs are organized as a tree: a top-level graph per project, sub-graphs nested inside modules, and markdown leaf pages at the bottom.

**Important**: This documentation set does **not** contain semantic edges between sibling nodes or cross-module interaction flows. You can navigate the parent-child hierarchy, but you will not see explicit "module A calls module B" relationships at the graph level. Infer cross-module connections from the prose content of leaf pages.

**Do not try to dump everything at once.** Drill down one layer at a time, guided by descriptions and search results.

## Documentation model

\`\`\`
{skillDir}/doc/{project}/
├── top.json              # project overview + top-level modules (edges are empty)
├── flows.json            # empty — no interaction flows in this variant
├── {Module}/
│   ├── {Module}.json     # sub-graph: description, codeScope, child nodes (edges are empty)
│   ├── {Leaf}.md         # leaf page: detailed doc for one component
│   └── {SubModule}/
│       ├── {SubModule}.json
│       └── ...
\`\`\`

A graph's child node either points to a deeper sub-graph (\`child.type == "graph"\`) or to a markdown leaf page (\`child.type == "page"\`). Each graph carries:
- \`description\` — what this module does
- \`codeScope\` — the exact source files/dirs this module documents
- \`nodes[]\` — child nodes with \`name\`, \`description\`, \`codeScope\`, \`child\`

Edges arrays exist but are always empty. The \`flows.json\` file contains no flows.

## The browse tool

Use \`scripts/browse.mjs\` (located in the doc-drill skill directory) to navigate:

\`\`\`bash
# Get project overview — see all top-level modules
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project}

# Drill into a module — see its children
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} {ModuleName}

# Keep drilling into sub-modules
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} {Module}/{SubModule}

# Read a leaf page when you've found the right component
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} {Module}/{LeafName} --read

# Search: find nodes by keyword across all levels
node {skillDir}/scripts/browse.mjs {skillDir}/doc {project} --search {keyword}
\`\`\`

Note: \`--flows\` is available but returns nothing useful in this documentation variant.

## Progressive-disclosure workflow

### 1. Orient — top-level overview
Run browse with just the project name. Read the module list and their descriptions. Since edges are empty, pay close attention to module names, descriptions, and codeScope to infer which modules might relate to your question.

### 2. Locate — drill broadly
Without edges or flows to guide you, expect to drill into **more modules than usual**. Pick 2–3 candidate modules based on descriptions and codeScope. Drill into each to see child nodes and their descriptions.

### 3. Focus — read leaf pages
Read the \`.md\` pages of relevant components with \`--read\`. **Look for cross-references within the prose** — mentions of other modules, function calls, data structures shared between components. These textual references replace the missing edge information.

### 4. Search — use liberally
Since structural navigation cues (edges, flows) are absent, rely on \`--search\` more heavily. Search for key terms, function names, or concepts from the question to find relevant nodes across the entire hierarchy.

### 5. Cross-reference
When a question spans multiple modules, you must piece together the connection by reading leaf pages from each module and finding where they reference each other. There is no edge or flow shortcut.

## Key principles

- **Lazy loading**: Still relevant — don't read every leaf page. Use descriptions and search to narrow down first
- **Description-guided navigation**: Without edges, module descriptions are your primary navigation signal. Read them carefully at every level
- **Search is your edge substitute**: When you need to find which module relates to a concept, search is faster than drilling every branch
- **codeScope is ground truth**: When mapping docs back to source files, read \`codeScope\`
- **Breadth before depth**: Especially important without edges — scan all sibling descriptions before committing to a drill path
- **Read for cross-references**: Leaf pages often mention other modules by name. These inline references are how you trace cross-module behavior

## Output conventions

When citing documentation findings:
- Use the module path as the citation: \`Core/SessionEngine/TurnLifecycle\`
- Note when you inferred a cross-module connection from leaf page content rather than from an explicit edge
- Mention source files from \`codeScope\` when the user needs to edit code
`.trimEnd();

export function getSkillContent(variant: "full" | "no-edges", project: string, skillDir: string): string {
  const template = variant === "full" ? SKILL_FULL : SKILL_NO_EDGES;
  return template.replaceAll("{project}", project).replaceAll("{skillDir}", skillDir);
}
